# Render Blueprint for mm2bet-admin
# Reference: https://render.com/docs/blueprint-spec

# Node.js service for the frontend
services:
  - type: web
    name: mm2bet-admin
    env: node
    nodeVersion: 16.17.0  # Use Node.js 16 LTS for better compatibility with Vue CLI
    buildCommand: |
      npm ci
      npx vue-cli-service build
    staticPublish: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VUE_APP_API_URL
        value: https://your-backend-api-url.com  # Replace with your actual backend URL
      - key: NPM_CONFIG_PRODUCTION
        value: 'false'  # Ensure devDependencies are installed
    build:
      cacheVersion: '1'  # Enable build caching for faster deployments

# Add database if needed
# databases:
#   - name: my-db
#     databaseName: mydb
#     user: myuser

# Add cron jobs if needed
# cronJobs:
#   - name: my-cron-job
#     schedule: "0 0 * * *"  # Runs daily at midnight
#     command: npm run my-script
